/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aritmatik;

/**
 *
 * @author USER
 */
public class NewJFrame extends javax.swing.JFrame {
String jns ="";
int jml;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jns = null;
        panel.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);  
        bil3.setVisible(false);
          bil4.setVisible(false);
          b1.setVisible(false);
          b2.setVisible(false);
          b3.setVisible(false);
          b4.setVisible(false);
          bt1.setVisible(false);
          t1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        jumbil = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        ket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jarit = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(255, 153, 153));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        jLabel2.setText("Jumlah Bilangan");
        panel.add(jLabel2);
        jLabel2.setBounds(20, 50, 100, 14);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 100, 110, 14);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 140, 100, 14);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 180, 110, 14);

        bt1.setText("HITUNG");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        panel.add(bt1);
        bt1.setBounds(150, 240, 90, 23);

        jumbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jumbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumbilActionPerformed(evt);
            }
        });
        panel.add(jumbil);
        jumbil.setBounds(150, 50, 130, 20);
        panel.add(b1);
        b1.setBounds(150, 90, 130, 30);
        panel.add(b2);
        b2.setBounds(150, 130, 130, 30);
        panel.add(b3);
        b3.setBounds(150, 170, 130, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 210, 110, 14);
        panel.add(b4);
        b4.setBounds(150, 200, 130, 30);

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 244, 110);
        panel.add(ket);
        ket.setBounds(100, 20, 100, 20);

        getContentPane().add(panel);
        panel.setBounds(70, 120, 370, 390);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 290, 29);

        jLabel7.setText("Jenis Aritmatik");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 90, 100, 14);

        jarit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Penjumlahan", "Pengurangan", "Pembagian", "Perkalian" }));
        jarit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaritActionPerformed(evt);
            }
        });
        getContentPane().add(jarit);
        jarit.setBounds(220, 90, 160, 20);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 580);

        setBounds(0, 0, 542, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void jaritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaritActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jaritActionPerformed

    private void jumbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumbilActionPerformed
        // TODO add your handling code here:
       getJumlah();
    }//GEN-LAST:event_jumbilActionPerformed

     public void getJumlah(){
        if(jumbil.getSelectedItem().equals("2")){
             bil1.setVisible(true);
             bil2.setVisible(true);
             bil3.setVisible(false);
             bil4.setVisible(false);
             b1.setVisible(true);
             b2.setVisible(true);
             b3.setVisible(false);
             b4.setVisible(false);
             bt1.setVisible(true);
             t1.setVisible(true);
             jml = 2;
        }
        else if(jumbil.getSelectedItem().equals("3")){
            bil1.setVisible(true);
          bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
             b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(false);
             bt1.setVisible(true);
             t1.setVisible(true);
            jml = 3;
        }
        else if(jumbil.getSelectedItem().equals("4")){
            bil1.setVisible(true);
          bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
             b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
             bt1.setVisible(true);
             t1.setVisible(true);
            jml = 4;
        }
        else {
          bil1.setVisible(false);
          bil2.setVisible(false);  
          bil3.setVisible(false);
          bil4.setVisible(false);
          b1.setVisible(false);
          b2.setVisible(false);
          b3.setVisible(false);
          b4.setVisible(false);
          
        }
    }
    public void setJenis(){
        if(jarit.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            jumbil.setEnabled(true);
        }
        else if(jarit.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            jumbil.setEnabled(true);
        } 
        else if(jarit.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            jumbil.setEnabled(true);
        } 
        else if(jarit.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            jumbil.setEnabled(true);
        } 
        else {
            jns = null;
            panel.setVisible(false);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                t1.setText(""+a1 + " + " + a2 + " = " + hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2 + a3;
                t1.setText(""+a1 + " + " + a2 + " + " + a3 + " = "  +  hsl);
        }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                t1.setText(""+a1 + " + " + a2 + " + " + a3 + " + " + a4 +  " = "  +  hsl);
        }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                t1.setText(""+a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                t1.setText(""+a1 + " - " + a2 + " - " + a3 + " = "  +  hsl);
        }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                t1.setText(""+a1 + " - " + a2 + " - " + a3 + " - " + a4 +  " = "  +  hsl);
        }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                t1.setText(""+a1 + " * " + a2 + " = " + hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                t1.setText(""+a1 + " x " + a2 + " x " + a3 + " = "  +  hsl);
        }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                t1.setText(""+a1 + " x " + a2 + " x " + a3 + " x " + a4 +  " = "  +  hsl);
        }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                t1.setText(""+a1 + " / " + a2 + " = " + hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                t1.setText(""+a1 + " / " + a2 + " / " + a3 + " = "  +  hsl);
        }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                t1.setText(""+a1 + " / " + a2 + " / " + a3 + " / " + a4 +  " = "  +  hsl);
        }
        }
    }//GEN-LAST:event_bt1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton bt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jarit;
    private javax.swing.JComboBox<String> jumbil;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
